package dnsserver

// defaultWarmupDomains is the embedded fallback list for cache warming.
// Used when the query log is empty (fresh install).
// Priority 2: Query-Log domains always take precedence (collectDomains).
var defaultWarmupDomains = []string{
	// DNS resolvers & infrastructure
	"dns.google",
	"cloudflare.com",
	"one.one.one.one",
	"dns9.quad9.net",
	"opendns.com",

	// Google services
	"google.com",
	"google.de",
	"googleapis.com",
	"gstatic.com",
	"googleusercontent.com",
	"googlevideo.com",
	"googletagmanager.com",
	"googleanalytics.com",
	"doubleclick.net",
	"youtube.com",
	"youtu.be",
	"ytimg.com",
	"ggpht.com",
	"gmail.com",
	"accounts.google.com",
	"play.google.com",
	"maps.google.com",
	"drive.google.com",

	// Microsoft / Azure
	"microsoft.com",
	"office.com",
	"office365.com",
	"microsoftonline.com",
	"outlook.com",
	"live.com",
	"hotmail.com",
	"azure.com",
	"azureedge.net",
	"windowsupdate.com",
	"update.microsoft.com",
	"teams.microsoft.com",
	"sharepoint.com",
	"onedrive.com",
	"bing.com",
	"msn.com",
	"visualstudio.com",
	"github.com",
	"githubusercontent.com",
	"ghcr.io",

	// Apple
	"apple.com",
	"icloud.com",
	"apple-dns.net",
	"itunes.com",
	"mzstatic.com",
	"icloud-content.com",
	"apple.akadns.net",

	// Meta / Facebook
	"facebook.com",
	"fbcdn.net",
	"fb.com",
	"instagram.com",
	"cdninstagram.com",
	"whatsapp.com",
	"whatsapp.net",
	"oculus.com",

	// Amazon / AWS
	"amazon.com",
	"amazon.de",
	"amazonaws.com",
	"cloudfront.net",
	"awsstatic.com",
	"amazonvideo.com",
	"primevideo.com",

	// CDNs & Cloud
	"cdn.cloudflare.net",
	"fastly.net",
	"akamaiedge.net",
	"akamaihd.net",
	"akamaitechnologies.com",
	"edgecastcdn.net",
	"stackpathcdn.com",
	"bootstrapcdn.com",
	"jsdelivr.net",
	"unpkg.com",
	"cdnjs.cloudflare.com",

	// Social Media
	"twitter.com",
	"x.com",
	"t.co",
	"twimg.com",
	"tiktok.com",
	"tiktokcdn.com",
	"snapchat.com",
	"snap.com",
	"linkedin.com",
	"licdn.com",
	"reddit.com",
	"redd.it",
	"redditstatic.com",
	"redditmedia.com",
	"pinterest.com",
	"tumblr.com",
	"discord.com",
	"discordapp.com",
	"discordapp.net",
	"twitch.tv",
	"twitchsvc.net",
	"jtvnw.net",

	// Streaming / Media
	"netflix.com",
	"nflxvideo.net",
	"nflximg.net",
	"nflxso.net",
	"spotify.com",
	"spotifycdn.com",
	"scdn.co",
	"soundcloud.com",
	"vimeo.com",
	"vimeocdn.com",
	"dailymotion.com",
	"deezer.com",

	// Tech & Developer
	"stackoverflow.com",
	"stackexchange.com",
	"stackimgur.com",
	"npmjs.com",
	"pypi.org",
	"registry.npmjs.org",
	"docker.com",
	"hub.docker.com",
	"quay.io",
	"gitlab.com",
	"bitbucket.org",
	"atlassian.com",
	"jira.atlassian.com",
	"confluence.atlassian.com",

	// News & Information
	"wikipedia.org",
	"wikimedia.org",
	"mediawiki.org",
	"bbc.com",
	"bbc.co.uk",
	"cnn.com",
	"spiegel.de",
	"zeit.de",
	"heise.de",
	"golem.de",
	"t3n.de",
	"nytimes.com",
	"theguardian.com",

	// E-Commerce
	"ebay.com",
	"ebay.de",
	"paypal.com",
	"paypalobjects.com",
	"etsy.com",
	"shopify.com",
	"shopifycdn.com",
	"aliexpress.com",
	"alibaba.com",
	"alicdn.com",
	"zalando.de",
	"otto.de",

	// Security & Telemetry
	"ocsp.digicert.com",
	"ocsp.globalsign.com",
	"crl.microsoft.com",
	"pki.goog",
	"lets-encrypt.org",
	"acme-v02.api.letsencrypt.org",
	"x1.i.lencr.org",

	// Open Source / Linux
	"kernel.org",
	"debian.org",
	"ubuntu.com",
	"archlinux.org",
	"fedoraproject.org",
	"centos.org",
	"opensuse.org",
	"gnu.org",
	"sourceforge.net",
	"launchpad.net",

	// Monitoring & Analytics
	"newrelic.com",
	"datadoghq.com",
	"sentry.io",
	"segment.com",
	"amplitude.com",
	"mixpanel.com",
	"grafana.com",
	"prometheus.io",

	// Communication / Email
	"sendgrid.net",
	"mailchimp.com",
	"sparkpostmail.com",
	"postmarkapp.com",
	"mandrillapp.com",
	"mailgun.org",
	"mailjet.com",
	"gmx.net",
	"gmx.de",
	"web.de",
	"protonmail.com",
	"tutanota.com",
	"fastmail.com",
	"zoho.com",

	// Gaming
	"steampowered.com",
	"steamcontent.com",
	"steamstatic.com",
	"valve.net",
	"epicgames.com",
	"ea.com",
	"origin.com",
	"battle.net",
	"blizzard.com",
	"gog.com",
	"ubisoft.com",

	// Finance
	"paypal.com",
	"stripe.com",
	"klarna.com",
	"adyen.com",
	"visa.com",
	"mastercard.com",

	// Maps & Navigation
	"openstreetmap.org",
	"tile.openstreetmap.org",
	"mapbox.com",
	"here.com",
	"tomtom.com",

	// Fonts & Assets
	"fonts.googleapis.com",
	"fonts.gstatic.com",
	"use.fontawesome.com",
	"maxcdn.bootstrapcdn.com",
	"code.jquery.com",
	"ajax.googleapis.com",
}
